# Generated by Django 5.2.3 on 2025-07-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=150),
        ),
    ]
