# Generated by Django 5.2.3 on 2025-06-28 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JefeDeGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos_app.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
