# Generated by Django 5.2.3 on 2025-06-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_app', '0002_jefedegrupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jefedegrupo',
            options={'verbose_name': 'Jefe de Grupo', 'verbose_name_plural': 'Jefes de Grupo'},
        ),
    ]
