# Generated by Django 5.2.3 on 2025-06-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GastosCompartidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_dirigidos', to='GastosCompartidos.jefedegrupo'),
        ),
    ]
