# Generated by Django 5.2.3 on 2025-06-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GastosCompartidos', '0002_alter_grupo_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefedegrupo',
            name='grupo',
        ),
    ]
