# Generated by Django 5.2.3 on 2025-06-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GastosCompartidos', '0003_remove_jefedegrupo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastocompartido',
            name='distribucion',
            field=models.CharField(choices=[('EQUITATIVO', 'Equitativo'), ('PROPORCIONAL', 'Proporcional'), ('PERSONALIZADO', 'Personalizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_dirigidos', to='GastosCompartidos.jefedegrupo'),
        ),
    ]
